import React, { useState, useRef } from 'react'

export default function CodeBlock({ children, ...props }: any) {
  const [copied, setCopied] = useState(false)
  const ref = useRef<HTMLElement>(null)

  // Only enhance figures generated by rehype-pretty-code
  if (!props['data-rehype-pretty-code-figure']) {
    return <figure {...props}>{children}</figure>
  }

  const handleCopy = () => {
    const pre = ref.current?.querySelector('pre')
    if (pre) {
      navigator.clipboard.writeText(pre.textContent || '')
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <figure ref={ref} className="group relative my-8 overflow-hidden rounded-md bg-[#22272e]" {...props}>
      <button 
        onClick={handleCopy}
        className="absolute right-3 top-3 z-10 flex h-7 w-7 items-center justify-center rounded border border-white/10 bg-white/5 text-white/50 opacity-0 backdrop-blur transition-all hover:bg-white/10 hover:text-white group-hover:opacity-100"
        aria-label="Copy code"
      >
        {copied ? (
          <svg className="h-3.5 w-3.5 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
          </svg>
        ) : (
          <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
            <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
        )}
      </button>
      {children}
    </figure>
  )
}
